CREATE TABLE [Lims].[Address](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Guidaddress] [uniqueidentifier] NOT NULL,
	[Address1] [nvarchar](256) NULL,
	[Address2] [nvarchar](256) NULL,
	[Address3] [nvarchar](256) NULL,
	[Phone] [nvarchar](16) NULL,
	[City] [nvarchar](256) NULL,
	[State] [bigint] NULL,
	[Country] [bigint] NULL,
	[Postalcode] [nvarchar](64) NULL,
	[Initialvalue] [bigint] NOT NULL,
	[Createddate] [datetimeoffset](7) NOT NULL,
	[Modifieddate] [datetimeoffset](7) NULL,
	[Deactivateddate] [datetimeoffset](7) NULL,
 CONSTRAINT [PK_Address] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
ALTER TABLE [Lims].[Audittrailmain] ADD  DEFAULT ((-1)) FOR [Idparent0]
ALTER TABLE [Lims].[Mlsummarydisposition] ADD  CONSTRAINT [Mlsummarydisposition_PK] PRIMARY KEY NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER TABLE [Lims].[Sysmlcountry] ADD  CONSTRAINT [DF__Sysmlcoun__Mlgui__3E52440B]  DEFAULT (newid()) FOR [Mlguid]
ALTER TABLE [Lims].[Audittrailmain]  WITH CHECK ADD  CONSTRAINT [Audittrailmain_FK00] FOREIGN KEY([Action])
REFERENCES [Lims].[Sysmlaudittrailaction] ([Id]) ON UPDATE CASCADE ON DELETE CASCADE

/****** Object:  Index [PK_Bacteria]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Bacteria] ADD  CONSTRAINT [PK_Bacteria] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_Buildings]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Buildings] ADD  CONSTRAINT [PK_Buildings] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_Classificati]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Classifications] ADD  CONSTRAINT [PK_Classificati] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_Departments]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Departments] ADD  CONSTRAINT [PK_Departments] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_DEPARTMENTSUT]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_DepartmentsUT] ADD  CONSTRAINT [PK_DEPARTMENTSUT] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_EmailOptions]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_EmailOptions] ADD  CONSTRAINT [PK_EmailOptions] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_EnviroProtocol]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_EnviroProtocol] ADD  CONSTRAINT [PK_EnviroProtocol] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_EnviroProtocolDetail]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_EnviroProtocolDetail] ADD  CONSTRAINT [PK_EnviroProtocolDetail] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_EnviroSummary]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_EnviroSummary] ADD  CONSTRAINT [PK_EnviroSummary] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_EnviroSumCellDet]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_EnviroSummaryCellDetail] ADD  CONSTRAINT [PK_EnviroSumCellDet] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_EnviroSummaryDetail]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  CONSTRAINT [PK_EnviroSummaryDetail] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_EnviroSummaryExtra]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_EnviroSummaryExtra] ADD  CONSTRAINT [PK_EnviroSummaryExtra] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_Equipment]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Equipments] ADD  CONSTRAINT [PK_Equipment] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_EQUIPMENTUSED]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_EquipmentUsed] ADD  CONSTRAINT [PK_EQUIPMENTUSED] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_Frequency]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Frequency] ADD  CONSTRAINT [PK_Frequency] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_FrequencyDetails]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_FrequencyDetails] ADD  CONSTRAINT [PK_FrequencyDetails] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_FrequencyOffset]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_FrequencyOffset] ADD  CONSTRAINT [PK_FrequencyOffset] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_GENUS]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Genus] ADD  CONSTRAINT [PK_GENUS] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [PK_Grades]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Grades] ADD  CONSTRAINT [PK_Grades] PRIMARY KEY NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_GramStains]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_GRAMSTAINS] ADD  CONSTRAINT [PK_GramStains] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_Incubators]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Incubators] ADD  CONSTRAINT [PK_Incubators] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_Ingredients]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Ingredients] ADD  CONSTRAINT [PK_Ingredients] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_Inventory]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Inventory] ADD  CONSTRAINT [PK_Inventory] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_InventoryLOTS]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_InventoryLots] ADD  CONSTRAINT [PK_InventoryLOTS] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_Investigations]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Investigations] ADD  CONSTRAINT [PK_Investigations] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_InvestigationTypes]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_InvestigationTypes] ADD  CONSTRAINT [PK_InvestigationTypes] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_Items]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Items] ADD  CONSTRAINT [PK_Items] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [PK_LocationDescriptions]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_LocationDescriptions] ADD  CONSTRAINT [PK_LocationDescriptions] PRIMARY KEY NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_Locations]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Locations] ADD  CONSTRAINT [PK_Locations] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_LogBacteria]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_LogBacteria] ADD  CONSTRAINT [PK_LogBacteria] PRIMARY KEY NONCLUSTERED 
(
	[CounterVal] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_LogChangeControl]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_LogChangeControl] ADD  CONSTRAINT [PK_LogChangeControl] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_Loops]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Loops] ADD  CONSTRAINT [PK_Loops] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_Manufacturers]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Manufacturers] ADD  CONSTRAINT [PK_Manufacturers] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_MEDIAUSED]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_MediaUsed] ADD  CONSTRAINT [PK_MEDIAUSED] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_Microbiologists]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Microbiologists] ADD  CONSTRAINT [PK_Microbiologists] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_ModifyList]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_ModifyList] ADD  CONSTRAINT [PK_ModifyList] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_NOTTAKENREASONS]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_NotTakenReasons] ADD  CONSTRAINT [PK_NOTTAKENREASONS] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [PK_PLANTS]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Plants] ADD  CONSTRAINT [PK_PLANTS] PRIMARY KEY NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UC_Barcode]    Script Date: 7/6/2023 11:33:18 AM ******/

SET ANSI_PADDING ON
GO
/****** Object:  Index [PK_PriorityLevels]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_PriorityLevels] ADD  CONSTRAINT [PK_PriorityLevels] PRIMARY KEY NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_ProdRecipeDet]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_ProductionRecipeDetails] ADD  CONSTRAINT [PK_ProdRecipeDet] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_ProdRecipes]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_ProductionRecipes] ADD  CONSTRAINT [PK_ProdRecipes] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_RecipeMasterAudit]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_RecipeMasterAuditTag] ADD  CONSTRAINT [PK_RecipeMasterAudit] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_RecipeProdAudit]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_RecipeProductionAuditTag] ADD  CONSTRAINT [PK_RecipeProdAudit] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_Recipes]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Recipes] ADD  CONSTRAINT [PK_Recipes] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_EM_ROLLINGSPECIFICATIONS]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_RollingSpecifications] ADD  CONSTRAINT [PK_EM_ROLLINGSPECIFICATIONS] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_Rooms]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Rooms] ADD  CONSTRAINT [PK_Rooms] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_RoomStatus]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_RoomStatus] ADD  CONSTRAINT [PK_RoomStatus] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_SampleGroups]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_SampleGroups] ADD  CONSTRAINT [PK_SampleGroups] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_SampleStatus]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_SampleStatus] ADD  CONSTRAINT [PK_SampleStatus] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_SPECIES]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Species] ADD  CONSTRAINT [PK_SPECIES] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_StorageLocations]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_StorageLocations] ADD  CONSTRAINT [PK_StorageLocations] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_STRAIN]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Strain] ADD  CONSTRAINT [PK_STRAIN] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_Suppliers]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Suppliers] ADD  CONSTRAINT [PK_Suppliers] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [aaaaaEM_Sys_EmailOptions_PK]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Sys_EmailOptions] ADD  CONSTRAINT [aaaaaEM_Sys_EmailOptions_PK] PRIMARY KEY NONCLUSTERED 
(
	[fldID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_TestDispositions]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_TestDispositions] ADD  CONSTRAINT [PK_TestDispositions] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_TestTypes]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_TestTypes] ADD  CONSTRAINT [PK_TestTypes] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_TESTTYPESUT]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_TestTypesUT] ADD  CONSTRAINT [PK_TESTTYPESUT] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_Units]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Units] ADD  CONSTRAINT [PK_Units] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_UTILITYTYPES]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_UtilityTypes] ADD  CONSTRAINT [PK_UTILITYTYPES] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [PK_Valves]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_Valves] ADD  CONSTRAINT [PK_Valves] PRIMARY KEY NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_WaterProtocol]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_WaterProtocol] ADD  CONSTRAINT [PK_WaterProtocol] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_WaterProtocolAuditTag]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_WaterProtocolAuditTag] ADD  CONSTRAINT [PK_WaterProtocolAuditTag] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_WaterProtocolDetail]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_WaterProtocolDetail] ADD  CONSTRAINT [PK_WaterProtocolDetail] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_WaterSpec]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_WaterSpec] ADD  CONSTRAINT [PK_WaterSpec] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_WaterSpecControlLevels]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_WaterSpecControlLevels] ADD  CONSTRAINT [PK_WaterSpecControlLevels] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_WaterSpecDetail]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_WaterSpecDetail] ADD  CONSTRAINT [PK_WaterSpecDetail] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_WaterSpecAudit]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_WaterSpecificationAuditTag] ADD  CONSTRAINT [PK_WaterSpecAudit] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_WaterSummary]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_WaterSummary] ADD  CONSTRAINT [PK_WaterSummary] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_WaterSummaryCellDetail]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_WaterSummaryCellDetail] ADD  CONSTRAINT [PK_WaterSummaryCellDetail] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_WaterSummaryDetail]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_WaterSummaryDetail] ADD  CONSTRAINT [PK_WaterSummaryDetail] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_WorkloadTotals]    Script Date: 7/6/2023 11:33:18 AM ******/
ALTER TABLE [dbo].[EM_WorkloadTotals] ADD  CONSTRAINT [PK_WorkloadTotals] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EM_AliasesTbl] ADD  DEFAULT ((0)) FOR [IsModifyList]
GO
ALTER TABLE [dbo].[EM_AliasesTbl] ADD  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[EM_AUDITTRAIL_MAIN] ADD  DEFAULT (getutcdate()) FOR [FLDDATE]
GO
ALTER TABLE [dbo].[EM_AUDITTRAIL_MAIN] ADD  DEFAULT ((-1)) FOR [FLDPARENTID_0]
GO
ALTER TABLE [dbo].[EM_AUDITTRAIL_MAIN] ADD  DEFAULT ((-1)) FOR [FLDPARENTID_1]
GO
ALTER TABLE [dbo].[EM_AUDITTRAIL_MAIN] ADD  DEFAULT ((-1)) FOR [FLDPARENTID_2]
GO
ALTER TABLE [dbo].[EM_AUDITTRAIL_MAIN] ADD  DEFAULT ((-1)) FOR [FLDPARENTID_3]
GO
ALTER TABLE [dbo].[EM_AUDITTRAIL_MAIN] ADD  DEFAULT ((-1)) FOR [FLDPARENTID_4]
GO
ALTER TABLE [dbo].[EM_Bacteria] ADD  DEFAULT ((0)) FOR [Pathogenic]
GO
ALTER TABLE [dbo].[EM_Bacteria] ADD  DEFAULT ((0)) FOR [Critical]
GO
ALTER TABLE [dbo].[EM_Bacteria] ADD  DEFAULT ((0)) FOR [Completed]
GO
ALTER TABLE [dbo].[EM_Bacteria] ADD  DEFAULT ((0)) FOR [Reviewed]
GO
ALTER TABLE [dbo].[EM_Bacteria] ADD  DEFAULT ((0)) FOR [Approved]
GO
ALTER TABLE [dbo].[EM_Bacteria] ADD  DEFAULT ((0)) FOR [Objectionable]
GO
ALTER TABLE [dbo].[EM_Bacteria] ADD  DEFAULT ((0)) FOR [Plant]
GO
ALTER TABLE [dbo].[EM_BacteriaApproved] ADD  DEFAULT ((0)) FOR [Completed]
GO
ALTER TABLE [dbo].[EM_BacteriaApproved] ADD  DEFAULT ((0)) FOR [Reviewed]
GO
ALTER TABLE [dbo].[EM_BacteriaApproved] ADD  DEFAULT ((0)) FOR [Approved]
GO
ALTER TABLE [dbo].[EM_BarcodeMaximum] ADD  DEFAULT ((0)) FOR [UserID]
GO
ALTER TABLE [dbo].[EM_Classifications] ADD  DEFAULT ((0)) FOR [ID_Category]
GO
ALTER TABLE [dbo].[EM_ENVIROOOS] ADD  DEFAULT ((0)) FOR [OOSBACTERIA]
GO
ALTER TABLE [dbo].[EM_ENVIROOOS] ADD  DEFAULT ((0)) FOR [OOSYEAST]
GO
ALTER TABLE [dbo].[EM_ENVIROOOS] ADD  DEFAULT ((0)) FOR [OOSTOTAL]
GO
ALTER TABLE [dbo].[EM_EnviroProtocol] ADD  DEFAULT ((0)) FOR [Plant]
GO
ALTER TABLE [dbo].[EM_EnviroProtocol] ADD  DEFAULT ((0)) FOR [Building]
GO
ALTER TABLE [dbo].[EM_EnviroProtocol] ADD  DEFAULT ((0)) FOR [Department]
GO
ALTER TABLE [dbo].[EM_EnviroProtocol] ADD  DEFAULT ((0)) FOR [Room]
GO
ALTER TABLE [dbo].[EM_EnviroProtocol] ADD  DEFAULT ((1)) FOR [ACTIVE]
GO
ALTER TABLE [dbo].[EM_EnviroProtocol] ADD  DEFAULT ((0)) FOR [Completed]
GO
ALTER TABLE [dbo].[EM_EnviroProtocol] ADD  DEFAULT ((0)) FOR [Reviewed]
GO
ALTER TABLE [dbo].[EM_EnviroProtocol] ADD  DEFAULT ((0)) FOR [Approved]
GO
ALTER TABLE [dbo].[EM_EnviroProtocol] ADD  DEFAULT ((0)) FOR [HasBeenGenerated]
GO
ALTER TABLE [dbo].[EM_EnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [ID_Type]
GO
ALTER TABLE [dbo].[EM_EnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [Room]
GO
ALTER TABLE [dbo].[EM_EnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [Location]
GO
ALTER TABLE [dbo].[EM_EnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [ID_Group]
GO
ALTER TABLE [dbo].[EM_EnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [ID_Microbiologist]
GO
ALTER TABLE [dbo].[EM_EnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [ID_LocationDescription]
GO
ALTER TABLE [dbo].[EM_EnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [ID_Classification]
GO
ALTER TABLE [dbo].[EM_EnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [Hours]
GO
ALTER TABLE [dbo].[EM_EnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [CostPerHour]
GO
ALTER TABLE [dbo].[EM_EnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [Bacteria]
GO
ALTER TABLE [dbo].[EM_EnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [Yeast]
GO
ALTER TABLE [dbo].[EM_EnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [Micro]
GO
ALTER TABLE [dbo].[EM_EnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [FreqStatic]
GO
ALTER TABLE [dbo].[EM_EnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [FreqDynamic]
GO
ALTER TABLE [dbo].[EM_EnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [SpecifyPerson]
GO
ALTER TABLE [dbo].[EM_EnviroSummary] ADD  DEFAULT ((0)) FOR [Plant]
GO
ALTER TABLE [dbo].[EM_EnviroSummary] ADD  DEFAULT ((0)) FOR [Building]
GO
ALTER TABLE [dbo].[EM_EnviroSummary] ADD  DEFAULT ((0)) FOR [Department]
GO
ALTER TABLE [dbo].[EM_EnviroSummary] ADD  DEFAULT ((0)) FOR [Room]
GO
ALTER TABLE [dbo].[EM_EnviroSummary] ADD  DEFAULT ((0)) FOR [Completed]
GO
ALTER TABLE [dbo].[EM_EnviroSummary] ADD  DEFAULT ((0)) FOR [Reviewed]
GO
ALTER TABLE [dbo].[EM_EnviroSummary] ADD  DEFAULT ((0)) FOR [Approved]
GO
ALTER TABLE [dbo].[EM_EnviroSummary] ADD  DEFAULT ((1)) FOR [Disposition]
GO
ALTER TABLE [dbo].[EM_EnviroSummary] ADD  DEFAULT ((1)) FOR [BatchNumber]
GO
ALTER TABLE [dbo].[EM_EnviroSummary] ADD  DEFAULT ((1)) FOR [NewSummary]
GO
ALTER TABLE [dbo].[EM_EnviroSummary] ADD  DEFAULT (getdate()) FOR [SamplingDate]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryCellDetail] ADD  DEFAULT ((0)) FOR [AuditTag]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryCellDetail] ADD  DEFAULT ((0)) FOR [SpecType]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryCellDetail] ADD  DEFAULT ((0)) FOR [GrdRow]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryCellDetail] ADD  DEFAULT ((0)) FOR [GrdCol]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryCellDetail] ADD  DEFAULT ((0)) FOR [ValueVal]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryCellDetail] ADD  DEFAULT ((0)) FOR [MicroID]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((1)) FOR [Shift]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [RoomStatus]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [ID_Classification]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [Location]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [Room]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [ID_Group]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [ID_Microbiologist]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [ID_LocationDescription]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [BacteriaInvestig]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [YeastInvestig]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [MicroInvestig]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [BacteriaID]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [YeastID]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [TotalID]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [ID_Type]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [SampleStatus]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [SpecifyPerson]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [ID_NotTakenReason]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [BacteriaInvalid]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [YeastInvalid]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [TotalInvalid]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [FrequencyID]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [AddedFromSummary]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((1)) FOR [Disposition]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [EquipUserID]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [OOSBACTERIA]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [OOSYEAST]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [OOSTOTAL]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [Completed]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [Reviewed]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [Approved]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [BarcodeAttached]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryExtra] ADD  DEFAULT ((0)) FOR [SpecType]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryExtra] ADD  DEFAULT ((0)) FOR [TakenBy]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryExtra] ADD  DEFAULT ((0)) FOR [HandledBy]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryExtra] ADD  DEFAULT ((0)) FOR [ReadBy]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryExtra] ADD  DEFAULT ((0)) FOR [NumRetests]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryExtra] ADD  DEFAULT ((1)) FOR [MultiplierValue]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryExtra] ADD  DEFAULT ((-1)) FOR [OccupantCount]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryExtra] ADD  DEFAULT ((0)) FOR [ApplyFormula]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryExtra] ADD  DEFAULT (getdate()) FOR [DateDone]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryExtra] ADD  DEFAULT (getdate()) FOR [DateEntered]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryExtra] ADD  DEFAULT (getdate()) FOR [DateComment]
GO
ALTER TABLE [dbo].[EM_Equipments] ADD  DEFAULT ((0)) FOR [ID]
GO
ALTER TABLE [dbo].[EM_Equipments] ADD  DEFAULT ((0)) FOR [FellerID]
GO
ALTER TABLE [dbo].[EM_FilterOrderByDetails] ADD  DEFAULT ((0)) FOR [OrderDirection]
GO
ALTER TABLE [dbo].[EM_Frequency] ADD  DEFAULT ((0)) FOR [IntervalTime]
GO
ALTER TABLE [dbo].[EM_Frequency] ADD  DEFAULT ((0)) FOR [RepeatTime]
GO
ALTER TABLE [dbo].[EM_Frequency] ADD  DEFAULT ((0)) FOR [DayOption]
GO
ALTER TABLE [dbo].[EM_Frequency] ADD  DEFAULT ((0)) FOR [DayTime]
GO
ALTER TABLE [dbo].[EM_Frequency] ADD  DEFAULT ((0)) FOR [OnTheOption]
GO
ALTER TABLE [dbo].[EM_Frequency] ADD  DEFAULT ((0)) FOR [OnThe1]
GO
ALTER TABLE [dbo].[EM_Frequency] ADD  DEFAULT ((0)) FOR [OnThe2]
GO
ALTER TABLE [dbo].[EM_FrequencyDetails] ADD  DEFAULT ((0)) FOR [Item]
GO
ALTER TABLE [dbo].[EM_FrequencyOffset] ADD  DEFAULT ((0)) FOR [Offset]
GO
ALTER TABLE [dbo].[EM_FrequencyOffset] ADD  DEFAULT ((0)) FOR [OffsetType]
GO
ALTER TABLE [dbo].[EM_GRAMSTAINS] ADD  DEFAULT ((0)) FOR [ID]
GO
ALTER TABLE [dbo].[EM_Inventory] ADD  DEFAULT ((0)) FOR [OriginalQuantity]
GO
ALTER TABLE [dbo].[EM_Inventory] ADD  DEFAULT ((0)) FOR [Quantity]
GO
ALTER TABLE [dbo].[EM_Inventory] ADD  DEFAULT ((0)) FOR [StorageLocation]
GO
ALTER TABLE [dbo].[EM_Inventory] ADD  DEFAULT ((0)) FOR [Quarantined]
GO
ALTER TABLE [dbo].[EM_Inventory] ADD  DEFAULT ((0)) FOR [Plant]
GO
ALTER TABLE [dbo].[EM_Inventory] ADD  DEFAULT (getdate()) FOR [ReceivedDate]
GO
ALTER TABLE [dbo].[EM_InventoryLots] ADD  DEFAULT ((0)) FOR [OriginalQuantity]
GO
ALTER TABLE [dbo].[EM_InventoryLots] ADD  DEFAULT ((0)) FOR [Quantity]
GO
ALTER TABLE [dbo].[EM_InventoryLots] ADD  DEFAULT ((0)) FOR [ID_StorageLocation]
GO
ALTER TABLE [dbo].[EM_Investigations] ADD  DEFAULT ((0)) FOR [Status]
GO
ALTER TABLE [dbo].[EM_Investigations] ADD  DEFAULT ((0)) FOR [ProtocolID]
GO
ALTER TABLE [dbo].[EM_Investigations] ADD  DEFAULT ((0)) FOR [ProdID]
GO
ALTER TABLE [dbo].[EM_Investigations] ADD  DEFAULT ((0)) FOR [ActionCompleted]
GO
ALTER TABLE [dbo].[EM_Investigations] ADD  DEFAULT ((0)) FOR [ActionApproved]
GO
ALTER TABLE [dbo].[EM_Investigations] ADD  DEFAULT ((0)) FOR [FollowUpCompleted]
GO
ALTER TABLE [dbo].[EM_Investigations] ADD  DEFAULT ((0)) FOR [FollowupApproved]
GO
ALTER TABLE [dbo].[EM_Investigations] ADD  DEFAULT ((0)) FOR [FinalCompleted]
GO
ALTER TABLE [dbo].[EM_Investigations] ADD  DEFAULT ((0)) FOR [Canceled]
GO
ALTER TABLE [dbo].[EM_Investigations] ADD  DEFAULT (getdate()) FOR [SummaryDate]
GO
ALTER TABLE [dbo].[EM_Investigations] ADD  DEFAULT ((0)) FOR [Plant]
GO
ALTER TABLE [dbo].[EM_Items] ADD  DEFAULT ((0)) FOR [Quantity]
GO
ALTER TABLE [dbo].[EM_LogBacteria] ADD  DEFAULT ((0)) FOR [BacteriaID]
GO
ALTER TABLE [dbo].[EM_LogBacteria] ADD  DEFAULT ((0)) FOR [SummaryDetailID]
GO
ALTER TABLE [dbo].[EM_LogBacteria] ADD  DEFAULT ((0)) FOR [LogReasonID]
GO
ALTER TABLE [dbo].[EM_LogBacteria] ADD  DEFAULT ((0)) FOR [Completed]
GO
ALTER TABLE [dbo].[EM_LogBacteria] ADD  DEFAULT ((0)) FOR [Reviewed]
GO
ALTER TABLE [dbo].[EM_LogBacteria] ADD  DEFAULT ((0)) FOR [Approved]
GO
ALTER TABLE [dbo].[EM_LogBacteria] ADD  DEFAULT ((0)) FOR [Objectionable]
GO
ALTER TABLE [dbo].[EM_LogChangeControl] ADD  DEFAULT ((0)) FOR [LOGREASONID]
GO
ALTER TABLE [dbo].[EM_LogChangeControl] ADD  DEFAULT ((0)) FOR [ID_USERACTIVITY]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtoCellDet] ADD  DEFAULT ((0)) FOR [ProtocolDetailID]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtoCellDet] ADD  DEFAULT ((0)) FOR [SpecID]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtoCellDet] ADD  DEFAULT ((0)) FOR [LogReasonID]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtoCellDet] ADD  DEFAULT ((0)) FOR [DynRangeUnit]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtoCellDet] ADD  DEFAULT ((0)) FOR [StatRangeUnit]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtoCellDet] ADD  DEFAULT ((0)) FOR [NA]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtocol] ADD  DEFAULT ((0)) FOR [ProtocolID]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtocol] ADD  DEFAULT ((0)) FOR [LogReasonID]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtocol] ADD  DEFAULT ((1)) FOR [ACTIVE]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtocol] ADD  DEFAULT ((0)) FOR [Completed]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtocol] ADD  DEFAULT ((0)) FOR [Reviewed]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtocol] ADD  DEFAULT ((0)) FOR [Approved]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [CounterVal]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [LogReasonID]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [ProtocolID]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [ID_Microbiologist]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [ID_LocationDescription]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [Hours]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [CostPerHour]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [Bacteria]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [Yeast]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [Micro]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [FreqStatic]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [FreqDynamic]
GO
ALTER TABLE [dbo].[EM_LogEnviroProtocolDetail] ADD  DEFAULT ((0)) FOR [SpecifyPerson]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummary] ADD  DEFAULT ((0)) FOR [LogReasonID]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummary] ADD  DEFAULT ((0)) FOR [SummaryID]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummary] ADD  DEFAULT ((0)) FOR [Completed]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummary] ADD  DEFAULT ((0)) FOR [Reviewed]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummary] ADD  DEFAULT ((0)) FOR [Approved]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummary] ADD  DEFAULT ((1)) FOR [Disposition]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummary] ADD  DEFAULT (getdate()) FOR [SamplingDate]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryCellDetail] ADD  DEFAULT ((0)) FOR [CounterVal]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryCellDetail] ADD  DEFAULT ((0)) FOR [LogReasonID]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryCellDetail] ADD  DEFAULT ((0)) FOR [SummaryDetailID]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryCellDetail] ADD  DEFAULT ((0)) FOR [SpecType]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryCellDetail] ADD  DEFAULT ((0)) FOR [GrdRow]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryCellDetail] ADD  DEFAULT ((0)) FOR [GrdCol]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryCellDetail] ADD  DEFAULT ((0)) FOR [ValueVal]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [CounterVal]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [LogReasonID]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [SummaryID]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [ID_Microbiologist]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [ID_LocationDescription]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryDetail] ADD  DEFAULT ((1)) FOR [Disposition]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [BacteriaInvalid]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [YeastInvalid]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [TotalInvalid]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [NumRetests]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [SpecifyPerson]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [SampleStatus]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryDetail] ADD  DEFAULT ((-1)) FOR [BacteriaInvestig]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryDetail] ADD  DEFAULT ((-1)) FOR [YeastInvestig]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryDetail] ADD  DEFAULT ((-1)) FOR [MicroInvestig]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [ID_NotTakenReason]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [Completed]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [Reviewed]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryDetail] ADD  DEFAULT ((0)) FOR [Approved]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryExtra] ADD  DEFAULT ((0)) FOR [NumRetests]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryExtra] ADD  DEFAULT ((-1)) FOR [OccupantCount]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryExtra] ADD  DEFAULT ((1)) FOR [MultiplierValue]
GO
ALTER TABLE [dbo].[EM_LogEnviroSummaryExtra] ADD  DEFAULT ((0)) FOR [ApplyFormula]
GO
ALTER TABLE [dbo].[EM_LogEquipmentUsed] ADD  DEFAULT (getdate()) FOR [LogDate]
GO
ALTER TABLE [dbo].[EM_LogInventory] ADD  DEFAULT ((0)) FOR [LogReasonID]
GO
ALTER TABLE [dbo].[EM_LogInventory] ADD  DEFAULT ((0)) FOR [OriginalQuantity]
GO
ALTER TABLE [dbo].[EM_LogInventory] ADD  DEFAULT ((0)) FOR [Quantity]
GO
ALTER TABLE [dbo].[EM_LogInventory] ADD  DEFAULT ((0)) FOR [StorageLocation]
GO
ALTER TABLE [dbo].[EM_LogInventory] ADD  DEFAULT ((0)) FOR [Quarantined]
GO
ALTER TABLE [dbo].[EM_LogInvestigations] ADD  DEFAULT ((0)) FOR [ActionApproved]
GO
ALTER TABLE [dbo].[EM_LogInvestigations] ADD  DEFAULT ((0)) FOR [ActionCompleted]
GO
ALTER TABLE [dbo].[EM_LogInvestigations] ADD  DEFAULT ((0)) FOR [FollowUpApproved]
GO
ALTER TABLE [dbo].[EM_LogInvestigations] ADD  DEFAULT ((0)) FOR [FollowUpCompleted]
GO
ALTER TABLE [dbo].[EM_LogInvestigations] ADD  DEFAULT ((0)) FOR [FinalCompleted]
GO
ALTER TABLE [dbo].[EM_LogInvestigations] ADD  DEFAULT ((0)) FOR [Canceled]
GO
ALTER TABLE [dbo].[EM_LogInvestigations] ADD  DEFAULT ((0)) FOR [ProtocolID]
GO
ALTER TABLE [dbo].[EM_LogMasterRecipe] ADD  DEFAULT ((0)) FOR [LogReasonID]
GO
ALTER TABLE [dbo].[EM_LogMasterRecipe] ADD  DEFAULT ((0)) FOR [RecipeID]
GO
ALTER TABLE [dbo].[EM_LogMasterRecipe] ADD  DEFAULT ((0)) FOR [BatchSize]
GO
ALTER TABLE [dbo].[EM_LogMasterRecipe] ADD  DEFAULT ((0)) FOR [Completed]
GO
ALTER TABLE [dbo].[EM_LogMasterRecipe] ADD  DEFAULT ((0)) FOR [Approved]
GO
ALTER TABLE [dbo].[EM_LogMasterRecipe] ADD  DEFAULT ((0)) FOR [Reviewed]
GO
ALTER TABLE [dbo].[EM_LogMasterRecipeDetail] ADD  DEFAULT ((0)) FOR [CounterVal]
GO
ALTER TABLE [dbo].[EM_LogMasterRecipeDetail] ADD  DEFAULT ((0)) FOR [LogReasonID]
GO
ALTER TABLE [dbo].[EM_LogMasterRecipeDetail] ADD  DEFAULT ((0)) FOR [RecipeID]
GO
ALTER TABLE [dbo].[EM_LogMediaUsed] ADD  DEFAULT (getdate()) FOR [LogDate]
GO
ALTER TABLE [dbo].[EM_LogProdRecipe] ADD  DEFAULT ((0)) FOR [LogReasonID]
GO
ALTER TABLE [dbo].[EM_LogProdRecipe] ADD  DEFAULT ((0)) FOR [RecipeID]
GO
ALTER TABLE [dbo].[EM_LogProdRecipe] ADD  DEFAULT ((0)) FOR [BatchSize]
GO
ALTER TABLE [dbo].[EM_LogProdRecipe] ADD  DEFAULT ((0)) FOR [Completed]
GO
ALTER TABLE [dbo].[EM_LogProdRecipe] ADD  DEFAULT ((0)) FOR [Approved]
GO
ALTER TABLE [dbo].[EM_LogProdRecipe] ADD  DEFAULT ((0)) FOR [Reviewed]
GO
ALTER TABLE [dbo].[EM_LogProdRecipe] ADD  DEFAULT ((0)) FOR [StorageLocation]
GO
ALTER TABLE [dbo].[EM_LogProdRecipeDetail] ADD  DEFAULT ((0)) FOR [CounterVal]
GO
ALTER TABLE [dbo].[EM_LogProdRecipeDetail] ADD  DEFAULT ((0)) FOR [LogReasonID]
GO
ALTER TABLE [dbo].[EM_LogProdRecipeDetail] ADD  DEFAULT ((0)) FOR [RecipeID]
GO
ALTER TABLE [dbo].[EM_LogUserActivity] ADD  DEFAULT ((0)) FOR [CounterVal]
GO
ALTER TABLE [dbo].[EM_LogUserActivity] ADD  DEFAULT ((0)) FOR [gID]
GO
ALTER TABLE [dbo].[EM_LogUserActivity] ADD  DEFAULT ((0)) FOR [SummaryDetail]
GO
ALTER TABLE [dbo].[EM_LogWaterProtocol] ADD  DEFAULT ((0)) FOR [ProtocolID]
GO
ALTER TABLE [dbo].[EM_LogWaterProtocol] ADD  DEFAULT ((0)) FOR [Completed]
GO
ALTER TABLE [dbo].[EM_LogWaterProtocol] ADD  DEFAULT ((0)) FOR [Reviewed]
GO
ALTER TABLE [dbo].[EM_LogWaterProtocol] ADD  DEFAULT ((0)) FOR [Approved]
GO
ALTER TABLE [dbo].[EM_LogWaterProtocol] ADD  DEFAULT ((1)) FOR [ACTIVE]
GO
ALTER TABLE [dbo].[EM_LogWaterProtocolDetail] ADD  DEFAULT ((0)) FOR [CounterVal]
GO
ALTER TABLE [dbo].[EM_LogWaterProtocolDetail] ADD  DEFAULT ((0)) FOR [ProtocolID]
GO
ALTER TABLE [dbo].[EM_LogWaterSpecDetail] ADD  DEFAULT ((0)) FOR [CounterVal]
GO
ALTER TABLE [dbo].[EM_LogWaterSpecDetail] ADD  DEFAULT ((0)) FOR [LogReasonID]
GO
ALTER TABLE [dbo].[EM_LogWaterSpecDetail] ADD  DEFAULT ((0)) FOR [SpecID]
GO
ALTER TABLE [dbo].[EM_LogWaterSpecDetail] ADD  DEFAULT ((0)) FOR [ID_ControlSpec]
GO
ALTER TABLE [dbo].[EM_LogWaterSpecDetail] ADD  DEFAULT ((0)) FOR [Minutes]
GO
ALTER TABLE [dbo].[EM_LogWaterSpecDetail] ADD  DEFAULT ((0)) FOR [Cost]
GO
ALTER TABLE [dbo].[EM_LogWaterSpecification] ADD  DEFAULT ((0)) FOR [Completed]
GO
ALTER TABLE [dbo].[EM_LogWaterSpecification] ADD  DEFAULT ((0)) FOR [Reviewed]
GO
ALTER TABLE [dbo].[EM_LogWaterSpecification] ADD  DEFAULT ((0)) FOR [Approved]
GO
ALTER TABLE [dbo].[EM_LogWaterSummary] ADD  DEFAULT ((0)) FOR [LogReasonID]
GO
ALTER TABLE [dbo].[EM_LogWaterSummary] ADD  DEFAULT ((0)) FOR [SummaryID]
GO
ALTER TABLE [dbo].[EM_LogWaterSummary] ADD  DEFAULT ((0)) FOR [Completed]
GO
ALTER TABLE [dbo].[EM_LogWaterSummary] ADD  DEFAULT ((0)) FOR [Reviewed]
GO
ALTER TABLE [dbo].[EM_LogWaterSummary] ADD  DEFAULT ((0)) FOR [Approved]
GO
ALTER TABLE [dbo].[EM_LogWaterSummary] ADD  DEFAULT (getdate()) FOR [SamplingDate]
GO
ALTER TABLE [dbo].[EM_LogWaterSummaryCellDetail] ADD  DEFAULT ((0)) FOR [CounterVal]
GO
ALTER TABLE [dbo].[EM_LogWaterSummaryCellDetail] ADD  DEFAULT ((0)) FOR [LogReasonID]
GO
ALTER TABLE [dbo].[EM_LogWaterSummaryCellDetail] ADD  DEFAULT ((0)) FOR [SummaryDetailID]
GO
ALTER TABLE [dbo].[EM_LogWaterSummaryCellDetail] ADD  DEFAULT ((0)) FOR [GrdRow]
GO
ALTER TABLE [dbo].[EM_LogWaterSummaryCellDetail] ADD  DEFAULT ((0)) FOR [GrdCol]
GO
ALTER TABLE [dbo].[EM_LogWaterSummaryCellDetail] ADD  DEFAULT ((0)) FOR [ValueVal]
GO
ALTER TABLE [dbo].[EM_LogWaterSummaryDetail] ADD  DEFAULT ((0)) FOR [CounterVal]
GO
ALTER TABLE [dbo].[EM_LogWaterSummaryDetail] ADD  DEFAULT ((0)) FOR [LogReasonID]
GO
ALTER TABLE [dbo].[EM_LogWaterSummaryDetail] ADD  DEFAULT ((0)) FOR [SummaryID]
GO
ALTER TABLE [dbo].[EM_LogWaterSummaryDetail] ADD  DEFAULT ((0)) FOR [SampleStatus]
GO
ALTER TABLE [dbo].[EM_LogWaterSummaryDetail] ADD  DEFAULT ((0)) FOR [Reason]
GO
ALTER TABLE [dbo].[EM_LogWaterSummaryDetail] ADD  DEFAULT ((0)) FOR [Spec]
GO
ALTER TABLE [dbo].[EM_LogWaterSummaryDetail] ADD  DEFAULT ((0)) FOR [InvestigID]
GO
ALTER TABLE [dbo].[EM_LogWaterSummaryDetail] ADD  DEFAULT ((0)) FOR [InvalidResult]
GO
ALTER TABLE [dbo].[EM_LogWaterSummaryDetail] ADD  DEFAULT ((0)) FOR [NumRetests]
GO
ALTER TABLE [dbo].[EM_LogWaterSummaryDetail] ADD  DEFAULT ((-1)) FOR [OccupantCount]
GO
ALTER TABLE [dbo].[EM_LogWaterSummaryDetail] ADD  DEFAULT ((1)) FOR [MultiplierValue]
GO
ALTER TABLE [dbo].[EM_LogWaterSummaryDetail] ADD  DEFAULT ((0)) FOR [OOS]
GO
ALTER TABLE [dbo].[EM_MapDetails] ADD  DEFAULT ((0)) FOR [Version]
GO
ALTER TABLE [dbo].[EM_Options] ADD  DEFAULT ((0)) FOR [AllowUsers]
GO
ALTER TABLE [dbo].[EM_Options] ADD  DEFAULT ((0)) FOR [AllowApproval]
GO
ALTER TABLE [dbo].[EM_Options] ADD  DEFAULT ((0)) FOR [DueDate]
GO
ALTER TABLE [dbo].[EM_Options] ADD  DEFAULT ((0)) FOR [GraceDays]
GO
ALTER TABLE [dbo].[EM_Options] ADD  DEFAULT ((30)) FOR [InventoryGracePeriod]
GO
ALTER TABLE [dbo].[EM_Options] ADD  DEFAULT ((1)) FOR [AllowOnDemand]
GO
ALTER TABLE [dbo].[EM_Options] ADD  DEFAULT ((30)) FOR [MaxGenDays]
GO
ALTER TABLE [dbo].[EM_Options] ADD  DEFAULT ((14)) FOR [DEFAULTDateRange]
GO
ALTER TABLE [dbo].[EM_Options] ADD  DEFAULT ((1)) FOR [AllowSummaryMicroID]
GO
ALTER TABLE [dbo].[EM_Options] ADD  DEFAULT ((1)) FOR [UseControlSpec]
GO
ALTER TABLE [dbo].[EM_Options] ADD  DEFAULT ((0)) FOR [RequireSummaryDisp]
GO
ALTER TABLE [dbo].[EM_Options] ADD  DEFAULT ((0)) FOR [RequireTestDisp]
GO
ALTER TABLE [dbo].[EM_Options] ADD  DEFAULT (' ') FOR [FooterText]
GO
ALTER TABLE [dbo].[EM_Options] ADD  DEFAULT ((0)) FOR [RoundUpNumber]
GO
ALTER TABLE [dbo].[EM_Options] ADD  DEFAULT ((7)) FOR [SpecToDisplay]
GO
ALTER TABLE [dbo].[EM_Options] ADD  DEFAULT ((0)) FOR [UseRequiredGridColor]
GO
ALTER TABLE [dbo].[EM_Options] ADD  DEFAULT ((0)) FOR [LEVELCONDITION]
GO
ALTER TABLE [dbo].[EM_PreLabeledMedia] ADD  DEFAULT (getutcdate()) FOR [EncodingDate]
GO
ALTER TABLE [dbo].[EM_PrelabledMediaBarcode] ADD  DEFAULT ((0)) FOR [Saved]
GO
ALTER TABLE [dbo].[EM_ProductionRecipes] ADD  DEFAULT ((0)) FOR [Completed]
GO
ALTER TABLE [dbo].[EM_ProductionRecipes] ADD  DEFAULT ((0)) FOR [Reviewed]
GO
ALTER TABLE [dbo].[EM_ProductionRecipes] ADD  DEFAULT ((0)) FOR [Approved]
GO
ALTER TABLE [dbo].[EM_ProductionRecipes] ADD  DEFAULT ((0)) FOR [Plant]
GO
ALTER TABLE [dbo].[EM_RecipeDetails] ADD  DEFAULT ((0)) FOR [ManufID]
GO
ALTER TABLE [dbo].[EM_RecipeDetails] ADD  DEFAULT ((0)) FOR [SupplierID]
GO
ALTER TABLE [dbo].[EM_Recipes] ADD  DEFAULT ((0)) FOR [BatchSize]
GO
ALTER TABLE [dbo].[EM_Recipes] ADD  DEFAULT ((0)) FOR [Completed]
GO
ALTER TABLE [dbo].[EM_Recipes] ADD  DEFAULT ((0)) FOR [Reviewed]
GO
ALTER TABLE [dbo].[EM_Recipes] ADD  DEFAULT ((0)) FOR [Approved]
GO
ALTER TABLE [dbo].[EM_Recipes] ADD  DEFAULT ((0)) FOR [Plant]
GO
ALTER TABLE [dbo].[EM_RequiredFields] ADD  DEFAULT ((0)) FOR [ISRequired]
GO
ALTER TABLE [dbo].[EM_RollingSpecifications] ADD  DEFAULT ((1)) FOR [Grouping]
GO
ALTER TABLE [dbo].[EM_SITE_ITEMS] ADD  DEFAULT ((0)) FOR [Quantity]
GO
ALTER TABLE [dbo].[EM_Specifications] ADD  DEFAULT ((0)) FOR [DynRangeUnit]
GO
ALTER TABLE [dbo].[EM_Specifications] ADD  DEFAULT ((0)) FOR [StatRangeUnit]
GO
ALTER TABLE [dbo].[EM_Specifications] ADD  DEFAULT ((0)) FOR [NA]
GO
ALTER TABLE [dbo].[EM_Specifications] ADD  DEFAULT ((0)) FOR [OptUsed]
GO
ALTER TABLE [dbo].[EM_Specifications] ADD  DEFAULT ((0)) FOR [Completed]
GO
ALTER TABLE [dbo].[EM_Specifications] ADD  DEFAULT ((0)) FOR [Reviewed]
GO
ALTER TABLE [dbo].[EM_Specifications] ADD  DEFAULT ((0)) FOR [Approved]
GO
ALTER TABLE [dbo].[EM_Specifications] ADD  DEFAULT ((0)) FOR [Plant]
GO
ALTER TABLE [dbo].[EM_Specifications] ADD  DEFAULT (getdate()) FOR [CompletedDate]
GO
ALTER TABLE [dbo].[EM_Specifications] ADD  DEFAULT (getdate()) FOR [ReviewedDate]
GO
ALTER TABLE [dbo].[EM_Specifications] ADD  DEFAULT (getdate()) FOR [ApprovedDate]
GO
ALTER TABLE [dbo].[EM_TblLogQueryDef] ADD  DEFAULT (getdate()) FOR [LogDate]
GO
ALTER TABLE [dbo].[EM_TblLogQueryDef] ADD  DEFAULT (getdate()) FOR [LogTime]
GO
ALTER TABLE [dbo].[EM_TblQueryDef] ADD  DEFAULT ((0)) FOR [QueryLock]
GO
ALTER TABLE [dbo].[EM_TestTypes] ADD  DEFAULT ((1)) FOR [IsViable]
GO
ALTER TABLE [dbo].[EM_TestTypes] ADD  DEFAULT ((1)) FOR [MultiplierValue]
GO
ALTER TABLE [dbo].[EM_TestTypes] ADD  DEFAULT ((0)) FOR [ID_Category]
GO
ALTER TABLE [dbo].[EM_UserEmail] ADD  DEFAULT ((0)) FOR [UserID]
GO
ALTER TABLE [dbo].[EM_UserEmail] ADD  DEFAULT ((0)) FOR [EmailOptions]
GO
ALTER TABLE [dbo].[EM_WaterProtocol] ADD  DEFAULT ((0)) FOR [Plant]
GO
ALTER TABLE [dbo].[EM_WaterProtocol] ADD  DEFAULT ((0)) FOR [Building]
GO
ALTER TABLE [dbo].[EM_WaterProtocol] ADD  DEFAULT ((0)) FOR [Department]
GO
ALTER TABLE [dbo].[EM_WaterProtocol] ADD  DEFAULT ((0)) FOR [Room]
GO
ALTER TABLE [dbo].[EM_WaterProtocol] ADD  DEFAULT ((0)) FOR [HasBeenGenerated]
GO
ALTER TABLE [dbo].[EM_WaterProtocol] ADD  DEFAULT ((0)) FOR [Completed]
GO
ALTER TABLE [dbo].[EM_WaterProtocol] ADD  DEFAULT ((0)) FOR [Reviewed]
GO
ALTER TABLE [dbo].[EM_WaterProtocol] ADD  DEFAULT ((0)) FOR [Approved]
GO
ALTER TABLE [dbo].[EM_WaterProtocol] ADD  DEFAULT ((1)) FOR [ACTIVE]
GO
ALTER TABLE [dbo].[EM_WaterProtocolDetail] ADD  DEFAULT ((0)) FOR [Plant]
GO
ALTER TABLE [dbo].[EM_WaterProtocolDetail] ADD  DEFAULT ((0)) FOR [Building]
GO
ALTER TABLE [dbo].[EM_WaterProtocolDetail] ADD  DEFAULT ((0)) FOR [Department]
GO
ALTER TABLE [dbo].[EM_WaterProtocolDetail] ADD  DEFAULT ((0)) FOR [Room]
GO
ALTER TABLE [dbo].[EM_WaterProtocolDetail] ADD  DEFAULT ((0)) FOR [ID_Loop]
GO
ALTER TABLE [dbo].[EM_WaterProtocolDetail] ADD  DEFAULT ((0)) FOR [Valve]
GO
ALTER TABLE [dbo].[EM_WaterProtocolDetail] ADD  DEFAULT ((0)) FOR [ID_Group]
GO
ALTER TABLE [dbo].[EM_WaterProtocolDetail] ADD  DEFAULT ((0)) FOR [Spec]
GO
ALTER TABLE [dbo].[EM_WaterProtocolDetail] ADD  DEFAULT ((0)) FOR [FreqID]
GO
ALTER TABLE [dbo].[EM_WaterSpec] ADD  DEFAULT ((0)) FOR [Completed]
GO
ALTER TABLE [dbo].[EM_WaterSpec] ADD  DEFAULT ((0)) FOR [Reviewed]
GO
ALTER TABLE [dbo].[EM_WaterSpec] ADD  DEFAULT ((0)) FOR [Approved]
GO
ALTER TABLE [dbo].[EM_WaterSpec] ADD  DEFAULT ((0)) FOR [Plant]
GO
ALTER TABLE [dbo].[EM_WaterSpecDetail] ADD  DEFAULT ((0)) FOR [ID_ControlSpec]
GO
ALTER TABLE [dbo].[EM_WaterSpecDetail] ADD  DEFAULT ((0)) FOR [Minutes]
GO
ALTER TABLE [dbo].[EM_WaterSpecDetail] ADD  DEFAULT ((0)) FOR [Cost]
GO
ALTER TABLE [dbo].[EM_WaterSummary] ADD  DEFAULT ((0)) FOR [Completed]
GO
ALTER TABLE [dbo].[EM_WaterSummary] ADD  DEFAULT ((0)) FOR [Reviewed]
GO
ALTER TABLE [dbo].[EM_WaterSummary] ADD  DEFAULT ((0)) FOR [Approved]
GO
ALTER TABLE [dbo].[EM_WaterSummary] ADD  DEFAULT ((0)) FOR [Plant]
GO
ALTER TABLE [dbo].[EM_WaterSummary] ADD  DEFAULT ((0)) FOR [Building]
GO
ALTER TABLE [dbo].[EM_WaterSummary] ADD  DEFAULT ((0)) FOR [Department]
GO
ALTER TABLE [dbo].[EM_WaterSummary] ADD  DEFAULT ((0)) FOR [Room]
GO
ALTER TABLE [dbo].[EM_WaterSummary] ADD  DEFAULT ((1)) FOR [BatchNumber]
GO
ALTER TABLE [dbo].[EM_WaterSummary] ADD  DEFAULT ((1)) FOR [Disposition]
GO
ALTER TABLE [dbo].[EM_WaterSummary] ADD  DEFAULT (getdate()) FOR [SamplingDate]
GO
ALTER TABLE [dbo].[EM_WaterSummaryCellDetail] ADD  DEFAULT ((0)) FOR [GrdRow]
GO
ALTER TABLE [dbo].[EM_WaterSummaryCellDetail] ADD  DEFAULT ((0)) FOR [GrdCol]
GO
ALTER TABLE [dbo].[EM_WaterSummaryDetail] ADD  DEFAULT ((0)) FOR [Plant]
GO
ALTER TABLE [dbo].[EM_WaterSummaryDetail] ADD  DEFAULT ((0)) FOR [Building]
GO
ALTER TABLE [dbo].[EM_WaterSummaryDetail] ADD  DEFAULT ((0)) FOR [Department]
GO
ALTER TABLE [dbo].[EM_WaterSummaryDetail] ADD  DEFAULT ((0)) FOR [Room]
GO
ALTER TABLE [dbo].[EM_WaterSummaryDetail] ADD  DEFAULT ((0)) FOR [ID_Group]
GO
ALTER TABLE [dbo].[EM_WaterSummaryDetail] ADD  DEFAULT ((0)) FOR [Valve]
GO
ALTER TABLE [dbo].[EM_WaterSummaryDetail] ADD  DEFAULT ((0)) FOR [ID_Loop]
GO
ALTER TABLE [dbo].[EM_WaterSummaryDetail] ADD  DEFAULT ((0)) FOR [SampleStatus]
GO
ALTER TABLE [dbo].[EM_WaterSummaryDetail] ADD  DEFAULT ((0)) FOR [ID_NotTakenReason]
GO
ALTER TABLE [dbo].[EM_WaterSummaryDetail] ADD  DEFAULT ((0)) FOR [Spec]
GO
ALTER TABLE [dbo].[EM_WaterSummaryDetail] ADD  DEFAULT ((0)) FOR [SampleTakenBy]
GO
ALTER TABLE [dbo].[EM_WaterSummaryDetail] ADD  DEFAULT ((0)) FOR [SampleHanBy]
GO
ALTER TABLE [dbo].[EM_WaterSummaryDetail] ADD  DEFAULT ((0)) FOR [SampleReadBy]
GO
ALTER TABLE [dbo].[EM_WaterSummaryDetail] ADD  DEFAULT ((0)) FOR [InvalidResult]
GO
ALTER TABLE [dbo].[EM_WaterSummaryDetail] ADD  DEFAULT ((0)) FOR [MicroID]
GO
ALTER TABLE [dbo].[EM_BacteriaApproved]  WITH CHECK ADD  CONSTRAINT [FK_BacteriaApproved] FOREIGN KEY([BacteriaID])
REFERENCES [dbo].[EM_Bacteria] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[EM_BacteriaApproved] CHECK CONSTRAINT [FK_BacteriaApproved]
GO
ALTER TABLE [dbo].[EM_ENVIROOOS]  WITH CHECK ADD  CONSTRAINT [FK_SUMMARYID_EM_ENVIROOOS] FOREIGN KEY([SUMMARYDETAILID])
REFERENCES [dbo].[EM_EnviroSummaryDetail] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[EM_ENVIROOOS] CHECK CONSTRAINT [FK_SUMMARYID_EM_ENVIROOOS]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryCellDetail]  WITH CHECK ADD  CONSTRAINT [FK_EnviroSummaryCellDetail] FOREIGN KEY([SummaryDetailID])
REFERENCES [dbo].[EM_EnviroSummaryDetail] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[EM_EnviroSummaryCellDetail] CHECK CONSTRAINT [FK_EnviroSummaryCellDetail]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail]  WITH CHECK ADD  CONSTRAINT [FK_ENVIROSUMMARYDETAIL] FOREIGN KEY([SummaryID])
REFERENCES [dbo].[EM_EnviroSummary] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[EM_EnviroSummaryDetail] CHECK CONSTRAINT [FK_ENVIROSUMMARYDETAIL]
GO
ALTER TABLE [dbo].[EM_EnviroSummaryExtra]  WITH CHECK ADD  CONSTRAINT [FK_EnviroSummaryExtra] FOREIGN KEY([SummaryDetailID])
REFERENCES [dbo].[EM_EnviroSummaryDetail] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[EM_EnviroSummaryExtra] CHECK CONSTRAINT [FK_EnviroSummaryExtra]
GO
ALTER TABLE [dbo].[EM_EquipmentUsed]  WITH CHECK ADD  CONSTRAINT [FK_EQUIPMENTUSED] FOREIGN KEY([ID_EnviroSummaryExtra])
REFERENCES [dbo].[EM_EnviroSummaryExtra] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[EM_EquipmentUsed] CHECK CONSTRAINT [FK_EQUIPMENTUSED]
GO
ALTER TABLE [dbo].[EM_EquipmentUsed]  WITH CHECK ADD  CONSTRAINT [FK_EQUIPMENTUSEDUT] FOREIGN KEY([ID_WaterSummaryDetail])
REFERENCES [dbo].[EM_WaterSummaryDetail] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[EM_EquipmentUsed] CHECK CONSTRAINT [FK_EQUIPMENTUSEDUT]
GO
ALTER TABLE [dbo].[EM_MediaUsed]  WITH CHECK ADD  CONSTRAINT [FK_MediaUsed] FOREIGN KEY([ID_EnviroSummaryExtra])
REFERENCES [dbo].[EM_EnviroSummaryExtra] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[EM_MediaUsed] CHECK CONSTRAINT [FK_MediaUsed]
GO
ALTER TABLE [dbo].[EM_MediaUsed]  WITH CHECK ADD  CONSTRAINT [FK_MEDIAUSEDINV] FOREIGN KEY([ID_Inventory])
REFERENCES [dbo].[EM_Inventory] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[EM_MediaUsed] CHECK CONSTRAINT [FK_MEDIAUSEDINV]
GO
ALTER TABLE [dbo].[EM_MediaUsed]  WITH CHECK ADD  CONSTRAINT [FK_MEDIAUSEDUT] FOREIGN KEY([ID_WaterSummaryDetail])
REFERENCES [dbo].[EM_WaterSummaryDetail] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[EM_MediaUsed] CHECK CONSTRAINT [FK_MEDIAUSEDUT]
GO
ALTER TABLE [dbo].[EM_PreLabeledMediaDetail]  WITH CHECK ADD  CONSTRAINT [FK_PreLabeledMedia] FOREIGN KEY([ID_Parent])
REFERENCES [dbo].[EM_PreLabeledMedia] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[EM_PreLabeledMediaDetail] CHECK CONSTRAINT [FK_PreLabeledMedia]
GO
